#!/usr/bin/env bash

sync_brand_assets() {
  log "Running Elite brand asset synchronization"

  [[ -x "$BRAND_SYNC_SCRIPT" ]] ||
    die "Brand sync script is missing or not executable: $BRAND_SYNC_SCRIPT"

  [[ -f "$BRAND_SYNC_CONFIG" ]] ||
    die "Brand sync configuration is missing: $BRAND_SYNC_CONFIG"

  local args=(
    --config "$BRAND_SYNC_CONFIG"
  )

  if [[ "$REOS_UI_DRY_RUN" -eq 1 ]]; then
    args+=(--dry-run)
  fi

  "$BRAND_SYNC_SCRIPT" "${args[@]}"
}

sync_ui_partials() {
  log "Synchronizing REOS UI partials"

  local name
  local source_file
  local target_file

  for name in BrandStyles.html BrandTheme.html; do
    source_file="$UI_TEMPLATE_ROOT/$name"
    target_file="$HTML_ROOT/$name"

    [[ -f "$source_file" ]] ||
      die "Missing UI template: $source_file"

    if [[ "$REOS_UI_DRY_RUN" -eq 1 ]]; then
      log "[DRY-RUN] Would copy $source_file to $target_file"
      continue
    fi

    mkdir -p "$HTML_ROOT"
    backup_file "$target_file"
    cp "$source_file" "$target_file"

    log "Updated: $target_file"
  done
}

inject_html_includes() {
  log "Checking HTML entry-point includes"

  local basename
  local html_file

  for basename in $HTML_ENTRY_FILES; do
    html_file="$HTML_ROOT/$basename"

    [[ -f "$html_file" ]] || {
      log "Entry file not found, skipping: $html_file"
      continue
    }

    if [[ "$REOS_UI_DRY_RUN" -eq 0 ]]; then
      backup_file "$html_file"
    fi

    python3 - "$html_file" "$REOS_UI_DRY_RUN" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
dry_run = sys.argv[2] == "1"

content = path.read_text(encoding="utf-8")

required = [
    "<?!= include('BrandStyles'); ?>",
    "<?!= include('BrandTheme'); ?>",
]

missing = [
    include
    for include in required
    if include not in content
]

if not missing:
    print(f"[HTML] Includes already present: {path}")
    raise SystemExit(0)

closing_head = re.search(
    r"</head\s*>",
    content,
    flags=re.IGNORECASE,
)

if closing_head is None:
    raise SystemExit(
        f"Unable to inject includes because </head> was not found: {path}"
    )

if dry_run:
    print(f"[HTML] [DRY-RUN] Would inject includes into: {path}")
    raise SystemExit(0)

include_block = (
    "\n"
    + "\n".join(f"  {item}" for item in missing)
    + "\n"
)

updated = (
    content[:closing_head.start()]
    + include_block
    + content[closing_head.start():]
)

path.write_text(updated, encoding="utf-8")

print(f"[HTML] Injected includes into: {path}")
PY
  done
}

generate_brand_config() {
  local input_file="$CONFIG_ROOT/brand.json"
  local output_file="$SRC_ROOT/BrandConfig.generated.gs"

  if [[ "$REOS_UI_DRY_RUN" -eq 1 ]]; then
    log "[DRY-RUN] Would generate $output_file from $input_file"
    return 0
  fi

  [[ -f "$input_file" ]] ||
    die "Brand configuration was not generated: $input_file"

  mkdir -p "$SRC_ROOT"
  backup_file "$output_file"

  python3 - "$input_file" "$output_file" <<'PY'
from pathlib import Path
import json
import sys

input_file = Path(sys.argv[1])
output_file = Path(sys.argv[2])

config = json.loads(
    input_file.read_text(encoding="utf-8")
)

payload = json.dumps(
    config,
    ensure_ascii=False,
    separators=(",", ":"),
)

source = f"""/**
 * AUTO-GENERATED FILE.
 *
 * Source: config/brand.json
 * Generator: REOS UI Build & Deploy SDK
 *
 * Do not edit this file manually.
 */
var REOS = REOS || {{}};

REOS.BrandConfigGenerated = Object.freeze({payload});

function getReosGeneratedBrandConfig() {{
  return JSON.parse(
    JSON.stringify(REOS.BrandConfigGenerated)
  );
}}
"""

output_file.write_text(source, encoding="utf-8")
PY

  log "Generated: $output_file"
}

sync_brand_ui_adapter() {
  local source_file="$SDK_ROOT/templates/src/BrandUi.gs"
  local target_file="$SRC_ROOT/BrandUi.gs"

  [[ -f "$source_file" ]] ||
    die "BrandUi template is missing: $source_file"

  if [[ "$REOS_UI_DRY_RUN" -eq 1 ]]; then
    log "[DRY-RUN] Would update: $target_file"
    return 0
  fi

  mkdir -p "$SRC_ROOT"
  backup_file "$target_file"
  cp "$source_file" "$target_file"

  log "Updated: $target_file"
}
